
#include "dl.h"
#include "kann-master/kann.h"
#include "apic.h"

#ifdef _DEBUG

#include "math.h"
#include "process.h"
#include "systemService.h"
#include "task.h"
#include "Pe.h"
#include "Thread.h"
#include "utils.h"

#else
#include "math.h"
#include "systemService.h"
#include "task.h"
#include "Pe.h"
#include "Thread.h"
#include "process.h"

#include "libc.h"
#include "malloc.h"
#include "deepLearning.h"
#endif

#define sqrt __sqrt
#define sqrtf __sqrtf
#define exp __exp
#define expf __expf
#define log __log
#define sin __sin
#define cos __cos
#define sinf __sinf
#define cosf __cosf
#define fabs __fabs
#define fabsf __fabsf
#define logf __logf


#define malloc my_malloc
#define free my_free
#define realloc my_realloc
#define calloc my_calloc

#define memcpy my_memcpy
#define memset	my_memset

#define abort my_abort

#define printf my_printf
#define fprintf my_fprintf

#define fread my_fread
#define fopen my_fopen
#define fwrite my_fwrite
#define fclose my_fclose
#define strcmp my_strcmp
#define strcat my_strcat
#define strlen my_strlen
#define strcpy my_strcpy
#define strncmp my_strncmp

#define wcslen my_wcslen
#define wcscmp my_wcscmp
#define wcscat my_wcscat
#define wcsstr my_wcsstr
#define wcscpy my_wcscpy

#define fputc my_fputc
#define fgetc my_fgetc
#define fgets my_fgets
#define fputs my_fputs



// to compile and run: gcc -O2 this-prog.c kann.c kautodiff.c -lm && ./a.out


void DlTestProcess(int tag) {

	g_dl_proc_tag = tag;

	int thread_cnt = ML_TASK_LIMIT - *(int*)(CPU_TOTAL_ADDRESS);

	int sleep_time = 0;

	for (int i = 0; i < thread_cnt; i++) {
		break;
		char tn[256];
		__sprintf(tn, "TestThread_%d", i);
		TASKCMDPARAMS cmd2;
		__memset((char*)&cmd2, 0, sizeof(TASKCMDPARAMS));
		DWORD ml_addr2 = getAddrFromName(MAIN_DLL_BASE, tn);
		if (ml_addr2) {
			__kCreateThread((unsigned int)ml_addr2, MAIN_DLL_SOURCE_BASE, (DWORD)&cmd2, tn);
			__sleep(sleep_time);
		}
	}

	int imageSize = getSizeOfImage((char*)MAIN_DLL_BASE);
	int sleep_cnt = ML_TASK_LIMIT / 2 - *(int*)(CPU_TOTAL_ADDRESS);
	for (int i = 0; i < sleep_cnt; ++i) {
		char tn[256];
		__sprintf(tn, "TestProcess_sleep_%d", i);

		DWORD addr = getAddrFromName(MAIN_DLL_BASE, tn);
		if (addr)
		{
			__kCreateProcess(MAIN_DLL_SOURCE_BASE, imageSize, "main.dll", tn, 3, 0);
			__sleep(sleep_time);
		}
	}

	int workcnt = ML_TASK_LIMIT / 2;
	for (int i = 0; i < workcnt; ++i) {
		char tn[256];
		__sprintf(tn, "TestProcess_work_%d", i);

		DWORD addr = getAddrFromName(MAIN_DLL_BASE, tn);
		if (addr)
		{
			__kCreateProcess(MAIN_DLL_SOURCE_BASE, imageSize, "main.dll", tn, 3, 0);
			__sleep(sleep_time);
		}
	}
}


extern "C" __declspec(dllexport) int DlMLPTraining(unsigned int retaddr, int tid, char* filename, char* funcname, DWORD param)
{
	printf("%s %d entry\r\n", __FUNCTION__, __LINE__);

	DWORD tick1 = *(DWORD*)CMOS_PERIOD_TICK_COUNT;

	__enterSpinlock(&g_dl_lock);

	g_dl_train_complete = 0;
	g_dl_rate = 0.0;

	if (g_dl_ann) {
		free(g_dl_ann);
		g_dl_ann = 0;
	}
	if (g_dl_data) {
		free(g_dl_data);
		g_dl_data = 0;
	}
	g_dl_data_cnt = 0;
	if (g_dl_data == 0 && g_dl_data_cnt == 0) {
		g_dl_data = (TaskPredictParam*)__kMalloc(TASK_DISPATCH_SAMPLE * sizeof(TaskPredictParam));
	}
	__leaveSpinlock(&g_dl_lock);

	if (g_dl_data == 0) {
		return 0;
	}

	printf("%s %d start\r\n", __FUNCTION__, __LINE__);

	DlTestProcess(0);

	printf("%s %d start\r\n", __FUNCTION__, __LINE__);

	while (g_dl_data_cnt < TASK_DISPATCH_SAMPLE) {
		__sleep(1000);
	}

	//__enterSpinlock(&g_dl_lock);

	printf("%s %d start\r\n", __FUNCTION__, __LINE__);

	DWORD tick2 = *(DWORD*)CMOS_PERIOD_TICK_COUNT;
	DWORD sampleTime = tick2 - tick1;

	char szout[256];

	int cnt = 0;
	int i = 0;
	int inSize = sizeof(TaskPredictParam) / sizeof(float) - 1;
	int n_samples = TASK_DISPATCH_SAMPLE;
	int outSize = ML_TASK_LIMIT;
	float** x, ** y, max, * x1;
	kad_node_t* t;
	
	// construct an MLP with one hidden layers
	t = kann_layer_input(inSize);

	t = kad_relu(kann_layer_dense(t, 64));
	//t = kad_relu(kann_layer_dense(t, 64));
	//t = kad_relu(kann_layer_dense(t, 64));

	//t = kann_layer_cost(t, 1, KANN_C_CEM); // output uses 1-hot encoding
	t = kann_layer_cost(t, outSize, KANN_C_CEM); // output uses 1-hot encoding

	g_dl_ann = kann_new(t, 0);

	// generate training data
	x = (float**)calloc(n_samples, sizeof(float*));
	y = (float**)calloc(n_samples, sizeof(float*));
	for (i = 0; i < n_samples; ++i) {

		x[i] = (float*)calloc(inSize, sizeof(float));
		__memcpy((char*)x[i], (char*) & g_dl_data[i], sizeof(TaskPredictParam) - sizeof(float));

		y[i] = (float*)calloc(outSize, sizeof(float));
		for (int j = 0; j < outSize; j++) {
			y[i][j] = 0.0;
		}
		int idx  = g_dl_data[i].result;
		if(idx != -1)
			y[i][idx] = 1.0;
	}

	printf("%s %d start\r\n", __FUNCTION__, __LINE__);
	// train
	kann_train_fnn1(g_dl_ann, 0.001f, 64, 50, 10, 0.1f, n_samples, x, y);

	printf("%s %d start\r\n", __FUNCTION__, __LINE__);
	// predict
	n_samples = TASK_DISPATCH_SAMPLE;
	x1 = (float*)calloc(inSize, sizeof(float));
	int n_err = 0;
	for (i = 0; i < n_samples; ++i) {
		__memcpy((char*)x1, (char*)&g_dl_data[i], sizeof(TaskPredictParam) - sizeof(float));

		const float* y1 = kann_apply1(g_dl_ann, x1);

		float max = -1.0;
		int num = 0;
		for (int j = 0; j < outSize; j++) {
			if (y1[j] > max) {
				max = y1[j];
				num = j;
			}
		}
#ifdef _DEBUG
		for (int j = 0; j < 16; j++) {
			printf("%d y:%lf tick:%f user:%f window:%f delta:%f priority:%f max:%f result:%d num:%d\r\n",
				j,y1[j],
				g_ml_data[i].task[j].tick, g_ml_data[i].task[j].user, g_ml_data[i].task[j].window,
				g_ml_data[i].task[j].delta, g_ml_data[i].task[j].priority,max, g_ml_data[i].result,num);
		}
#endif
		if (g_dl_data[i].result != -1) {
			if (num != g_dl_data[i].result) {
				n_err++;
			}
		}
	}

	tick1 = *(DWORD*)CMOS_PERIOD_TICK_COUNT;
	DWORD trainTime = tick1 - tick2;

	double error = 100.0 * n_err / n_samples;
	printf("Task Prediction sample:%d, input dimension:%d, output dimension:%d, error rate: %lf%%, sample seconds:%d, train seconds:%d\r\n", 
		TASK_DISPATCH_SAMPLE, inSize,outSize,error, sampleTime,trainTime);
	g_dl_rate = error;
	//kann_delete(ann); // TODO: also to free x, y and x1
	if (error< TASK_DISPATCH_ERROR_RATE) {
		g_dl_train_complete = 1;
	}

	//__leaveSpinlock(&g_dl_lock);

	return 0;
}

typedef struct {
	int n_in, ulen;
	int n, m;
	uint64_t* x, * y;
} bit_data_t;

static void train(kann_t* ann, bit_data_t* d, float lr, int mini_size, int max_epoch, const char* fn, int n_threads)
{
	float** x, ** y, * r, best_cost = 1e30f;
	int epoch, j, n_var, * shuf;
	kann_t* ua;

	n_var = kann_size_var(ann);
	r = (float*)calloc(n_var, sizeof(float));
	x = (float**)malloc(d->ulen * sizeof(float*));
	y = (float**)malloc(d->ulen * sizeof(float*));
	for (j = 0; j < d->ulen; ++j) {
		x[j] = (float*)calloc(mini_size * d->n_in, sizeof(float));
		y[j] = (float*)calloc(mini_size * 2, sizeof(float));
	}
	shuf = (int*)calloc(d->n, sizeof(int));
	kann_shuffle(d->n, shuf);

	ua = kann_unroll(ann, d->ulen);
	kann_set_batch_size(ua, mini_size);
	kann_mt(ua, n_threads, mini_size);
	kann_feed_bind(ua, KANN_F_IN, 0, x);
	kann_feed_bind(ua, KANN_F_TRUTH, 0, y);
	kann_switch(ua, 1);
	for (epoch = 0; epoch < max_epoch; ++epoch) {
		double cost = 0.0;
		int tot = 0, tot_base = 0, n_cerr = 0;
		for (j = 0; j < d->n - mini_size; j += mini_size) {
			int i, b, k;
			for (k = 0; k < d->ulen; ++k) {
				for (b = 0; b < mini_size; ++b) {
					int s = shuf[j + b];
					for (i = 0; i < d->n_in; ++i)
						x[k][b * d->n_in + i] = (float)(d->x[s * d->n_in + i] >> k & 1);
					y[k][b * 2] = y[k][b * 2 + 1] = 0.0f;
					y[k][b * 2 + (d->y[s] >> k & 1)] = 1.0f;
				}
			}
			cost += kann_cost(ua, 0, 1) * d->ulen * mini_size;
			n_cerr += kann_class_error(ua, &k);
			tot_base += k;
			//kad_check_grad(ua->n, ua->v, ua->n-1);
			kann_RMSprop(n_var, lr, 0, 0.9f, ua->g, ua->x, r);
			tot += d->ulen * mini_size;
		}
		if (cost < best_cost) {
			best_cost = cost;
			if (fn) kann_save(fn, ann);
		}
		fprintf(stderr, "epoch: %d; cost: %g (class error: %.2f%%)\n", epoch + 1, cost / tot, 100.0f * n_cerr / tot_base);
	}

	for (j = 0; j < d->ulen; ++j) {
		free(y[j]); free(x[j]);
	}
	free(y); free(x); free(r); free(shuf);
}



extern "C" __declspec(dllexport) int DlRNNTraining(unsigned int retaddr, int tid, char* filename, char* funcname, DWORD param)
{
	int i, c, seed = 11, n_h_layers = 1, n_h_neurons = 64, mini_size = 64, max_epoch = 30, to_apply = 0, norm = 1, n_threads = 1;
	float lr = 0.01f, dropout = 0.2f;
	kann_t* ann = 0;
	char* fn_in = 0, * fn_out = 0;

	int inSize = sizeof(TaskPredictParam) / sizeof(float) - 1;
	int blockSize = sizeof(TaskPredictParam) - sizeof(float);

	int n_samples = TASK_DISPATCH_SAMPLE;
	int outSize = 1;

	kad_node_t* t;
	int rnn_flag = KANN_RNN_VAR_H0;
	if (norm) rnn_flag |= KANN_RNN_NORM;
	bit_data_t *d = (bit_data_t*)malloc(sizeof(bit_data_t));
	d->n_in = inSize;
	d->m = TASK_DISPATCH_SAMPLE;
	d->n = TASK_DISPATCH_SAMPLE;
	d->ulen = 32;
	d->x = (unsigned long long*)malloc(inSize*sizeof(float) * TASK_DISPATCH_SAMPLE);
	d->y = (unsigned long long*)malloc(sizeof(float)* TASK_DISPATCH_SAMPLE);

	if (g_dl_data == 0) {
		g_dl_data = (TaskPredictParam*)malloc(TASK_DISPATCH_SAMPLE *sizeof(TaskPredictParam));
	}

	for (i = 0; i < n_samples; ++i) {

		__memcpy((char*)d->x + i* blockSize, (char*)&g_dl_data[i], blockSize);

		int idx = g_dl_data[i].result;
		d->y[i] = idx*1.0;
	}

	t = kann_layer_input(d->n_in);
	for (i = 0; i < n_h_layers; ++i) {
		t = kann_layer_gru(t, n_h_neurons, rnn_flag);
		t = kann_layer_dropout(t, dropout);
	}
	ann = kann_new(kann_layer_cost(t, 2, KANN_C_CEM), 0);
	
	train(ann, d, lr, mini_size, max_epoch, fn_out, n_threads);

	return 0;
}







int g_dl_proc_tag = 0;









#define DEFINE_TEST_PROCESS_SLEEP(N) \
    extern "C" __declspec(dllexport) void TestProcess_sleep_##N() { \
        while( (g_dl_train_complete == 0 && g_dl_rate == 0.0) || g_dl_proc_tag ){\
			__sleep(0);\
		} \
    }



#define DEFINE_TEST_PROCESS_WORK(N) \
    extern "C" __declspec(dllexport) void TestProcess_work_##N() { \
        while( (g_dl_train_complete == 0 && g_dl_rate == 0.0)||g_dl_proc_tag  )\
		{\
			char data[1024]; \
			__memset(data,0,1024); \
		 } \
    }

DEFINE_TEST_PROCESS_WORK(0)
DEFINE_TEST_PROCESS_WORK(1)
DEFINE_TEST_PROCESS_WORK(2)
DEFINE_TEST_PROCESS_WORK(3)
DEFINE_TEST_PROCESS_WORK(4)
DEFINE_TEST_PROCESS_WORK(5)
DEFINE_TEST_PROCESS_WORK(6)
DEFINE_TEST_PROCESS_WORK(7)
DEFINE_TEST_PROCESS_WORK(8)
DEFINE_TEST_PROCESS_WORK(9)
DEFINE_TEST_PROCESS_WORK(10)
DEFINE_TEST_PROCESS_WORK(11)
DEFINE_TEST_PROCESS_WORK(12)
DEFINE_TEST_PROCESS_WORK(13)
DEFINE_TEST_PROCESS_WORK(14)
DEFINE_TEST_PROCESS_WORK(15)
DEFINE_TEST_PROCESS_WORK(16)
DEFINE_TEST_PROCESS_WORK(17)
DEFINE_TEST_PROCESS_WORK(18)
DEFINE_TEST_PROCESS_WORK(19)
DEFINE_TEST_PROCESS_WORK(20)
DEFINE_TEST_PROCESS_WORK(21)
DEFINE_TEST_PROCESS_WORK(22)
DEFINE_TEST_PROCESS_WORK(23)
DEFINE_TEST_PROCESS_WORK(24)
DEFINE_TEST_PROCESS_WORK(25)
DEFINE_TEST_PROCESS_WORK(26)
DEFINE_TEST_PROCESS_WORK(27)
DEFINE_TEST_PROCESS_WORK(28)
DEFINE_TEST_PROCESS_WORK(29)
DEFINE_TEST_PROCESS_WORK(30)
DEFINE_TEST_PROCESS_WORK(31)
DEFINE_TEST_PROCESS_WORK(32)
DEFINE_TEST_PROCESS_WORK(33)
DEFINE_TEST_PROCESS_WORK(34)
DEFINE_TEST_PROCESS_WORK(35)
DEFINE_TEST_PROCESS_WORK(36)
DEFINE_TEST_PROCESS_WORK(37)
DEFINE_TEST_PROCESS_WORK(38)
DEFINE_TEST_PROCESS_WORK(39)
DEFINE_TEST_PROCESS_WORK(40)
DEFINE_TEST_PROCESS_WORK(41)
DEFINE_TEST_PROCESS_WORK(42)
DEFINE_TEST_PROCESS_WORK(43)
DEFINE_TEST_PROCESS_WORK(44)
DEFINE_TEST_PROCESS_WORK(45)
DEFINE_TEST_PROCESS_WORK(46)
DEFINE_TEST_PROCESS_WORK(47)
DEFINE_TEST_PROCESS_WORK(48)
DEFINE_TEST_PROCESS_WORK(49)
DEFINE_TEST_PROCESS_WORK(50)
DEFINE_TEST_PROCESS_WORK(51)
DEFINE_TEST_PROCESS_WORK(52)
DEFINE_TEST_PROCESS_WORK(53)
DEFINE_TEST_PROCESS_WORK(54)
DEFINE_TEST_PROCESS_WORK(55)
DEFINE_TEST_PROCESS_WORK(56)
DEFINE_TEST_PROCESS_WORK(57)
DEFINE_TEST_PROCESS_WORK(58)
DEFINE_TEST_PROCESS_WORK(59)
DEFINE_TEST_PROCESS_WORK(60)
DEFINE_TEST_PROCESS_WORK(61)
DEFINE_TEST_PROCESS_WORK(62)
DEFINE_TEST_PROCESS_WORK(63)
DEFINE_TEST_PROCESS_WORK(64)
DEFINE_TEST_PROCESS_WORK(65)
DEFINE_TEST_PROCESS_WORK(66)
DEFINE_TEST_PROCESS_WORK(67)
DEFINE_TEST_PROCESS_WORK(68)
DEFINE_TEST_PROCESS_WORK(69)
DEFINE_TEST_PROCESS_WORK(70)
DEFINE_TEST_PROCESS_WORK(71)
DEFINE_TEST_PROCESS_WORK(72)
DEFINE_TEST_PROCESS_WORK(73)
DEFINE_TEST_PROCESS_WORK(74)
DEFINE_TEST_PROCESS_WORK(75)
DEFINE_TEST_PROCESS_WORK(76)
DEFINE_TEST_PROCESS_WORK(77)
DEFINE_TEST_PROCESS_WORK(78)
DEFINE_TEST_PROCESS_WORK(79)
DEFINE_TEST_PROCESS_WORK(80)
DEFINE_TEST_PROCESS_WORK(81)
DEFINE_TEST_PROCESS_WORK(82)
DEFINE_TEST_PROCESS_WORK(83)
DEFINE_TEST_PROCESS_WORK(84)
DEFINE_TEST_PROCESS_WORK(85)
DEFINE_TEST_PROCESS_WORK(86)
DEFINE_TEST_PROCESS_WORK(87)
DEFINE_TEST_PROCESS_WORK(88)
DEFINE_TEST_PROCESS_WORK(89)
DEFINE_TEST_PROCESS_WORK(90)
DEFINE_TEST_PROCESS_WORK(91)
DEFINE_TEST_PROCESS_WORK(92)
DEFINE_TEST_PROCESS_WORK(93)
DEFINE_TEST_PROCESS_WORK(94)
DEFINE_TEST_PROCESS_WORK(95)
DEFINE_TEST_PROCESS_WORK(96)
DEFINE_TEST_PROCESS_WORK(97)
DEFINE_TEST_PROCESS_WORK(98)
DEFINE_TEST_PROCESS_WORK(99)
DEFINE_TEST_PROCESS_WORK(100)
DEFINE_TEST_PROCESS_WORK(101)
DEFINE_TEST_PROCESS_WORK(102)
DEFINE_TEST_PROCESS_WORK(103)
DEFINE_TEST_PROCESS_WORK(104)
DEFINE_TEST_PROCESS_WORK(105)
DEFINE_TEST_PROCESS_WORK(106)
DEFINE_TEST_PROCESS_WORK(107)
DEFINE_TEST_PROCESS_WORK(108)
DEFINE_TEST_PROCESS_WORK(109)
DEFINE_TEST_PROCESS_WORK(110)
DEFINE_TEST_PROCESS_WORK(111)
DEFINE_TEST_PROCESS_WORK(112)
DEFINE_TEST_PROCESS_WORK(113)
DEFINE_TEST_PROCESS_WORK(114)
DEFINE_TEST_PROCESS_WORK(115)
DEFINE_TEST_PROCESS_WORK(116)
DEFINE_TEST_PROCESS_WORK(117)
DEFINE_TEST_PROCESS_WORK(118)
DEFINE_TEST_PROCESS_WORK(119)
DEFINE_TEST_PROCESS_WORK(120)
DEFINE_TEST_PROCESS_WORK(121)
DEFINE_TEST_PROCESS_WORK(122)
DEFINE_TEST_PROCESS_WORK(123)
DEFINE_TEST_PROCESS_WORK(124)
DEFINE_TEST_PROCESS_WORK(125)
DEFINE_TEST_PROCESS_WORK(126)
DEFINE_TEST_PROCESS_WORK(127)
DEFINE_TEST_PROCESS_WORK(128)
DEFINE_TEST_PROCESS_WORK(129)
DEFINE_TEST_PROCESS_WORK(130)
DEFINE_TEST_PROCESS_WORK(131)
DEFINE_TEST_PROCESS_WORK(132)
DEFINE_TEST_PROCESS_WORK(133)
DEFINE_TEST_PROCESS_WORK(134)
DEFINE_TEST_PROCESS_WORK(135)
DEFINE_TEST_PROCESS_WORK(136)
DEFINE_TEST_PROCESS_WORK(137)
DEFINE_TEST_PROCESS_WORK(138)
DEFINE_TEST_PROCESS_WORK(139)
DEFINE_TEST_PROCESS_WORK(140)
DEFINE_TEST_PROCESS_WORK(141)
DEFINE_TEST_PROCESS_WORK(142)
DEFINE_TEST_PROCESS_WORK(143)
DEFINE_TEST_PROCESS_WORK(144)
DEFINE_TEST_PROCESS_WORK(145)
DEFINE_TEST_PROCESS_WORK(146)
DEFINE_TEST_PROCESS_WORK(147)
DEFINE_TEST_PROCESS_WORK(148)
DEFINE_TEST_PROCESS_WORK(149)
DEFINE_TEST_PROCESS_WORK(150)
DEFINE_TEST_PROCESS_WORK(151)
DEFINE_TEST_PROCESS_WORK(152)
DEFINE_TEST_PROCESS_WORK(153)
DEFINE_TEST_PROCESS_WORK(154)
DEFINE_TEST_PROCESS_WORK(155)
DEFINE_TEST_PROCESS_WORK(156)
DEFINE_TEST_PROCESS_WORK(157)
DEFINE_TEST_PROCESS_WORK(158)
DEFINE_TEST_PROCESS_WORK(159)
DEFINE_TEST_PROCESS_WORK(160)
DEFINE_TEST_PROCESS_WORK(161)
DEFINE_TEST_PROCESS_WORK(162)
DEFINE_TEST_PROCESS_WORK(163)
DEFINE_TEST_PROCESS_WORK(164)
DEFINE_TEST_PROCESS_WORK(165)
DEFINE_TEST_PROCESS_WORK(166)
DEFINE_TEST_PROCESS_WORK(167)
DEFINE_TEST_PROCESS_WORK(168)
DEFINE_TEST_PROCESS_WORK(169)
DEFINE_TEST_PROCESS_WORK(170)
DEFINE_TEST_PROCESS_WORK(171)
DEFINE_TEST_PROCESS_WORK(172)
DEFINE_TEST_PROCESS_WORK(173)
DEFINE_TEST_PROCESS_WORK(174)
DEFINE_TEST_PROCESS_WORK(175)
DEFINE_TEST_PROCESS_WORK(176)
DEFINE_TEST_PROCESS_WORK(177)
DEFINE_TEST_PROCESS_WORK(178)
DEFINE_TEST_PROCESS_WORK(179)
DEFINE_TEST_PROCESS_WORK(180)
DEFINE_TEST_PROCESS_WORK(181)
DEFINE_TEST_PROCESS_WORK(182)
DEFINE_TEST_PROCESS_WORK(183)
DEFINE_TEST_PROCESS_WORK(184)
DEFINE_TEST_PROCESS_WORK(185)
DEFINE_TEST_PROCESS_WORK(186)
DEFINE_TEST_PROCESS_WORK(187)
DEFINE_TEST_PROCESS_WORK(188)
DEFINE_TEST_PROCESS_WORK(189)
DEFINE_TEST_PROCESS_WORK(190)
DEFINE_TEST_PROCESS_WORK(191)
DEFINE_TEST_PROCESS_WORK(192)
DEFINE_TEST_PROCESS_WORK(193)
DEFINE_TEST_PROCESS_WORK(194)
DEFINE_TEST_PROCESS_WORK(195)
DEFINE_TEST_PROCESS_WORK(196)
DEFINE_TEST_PROCESS_WORK(197)
DEFINE_TEST_PROCESS_WORK(198)
DEFINE_TEST_PROCESS_WORK(199)
DEFINE_TEST_PROCESS_WORK(200)
DEFINE_TEST_PROCESS_WORK(201)
DEFINE_TEST_PROCESS_WORK(202)
DEFINE_TEST_PROCESS_WORK(203)
DEFINE_TEST_PROCESS_WORK(204)
DEFINE_TEST_PROCESS_WORK(205)
DEFINE_TEST_PROCESS_WORK(206)
DEFINE_TEST_PROCESS_WORK(207)
DEFINE_TEST_PROCESS_WORK(208)
DEFINE_TEST_PROCESS_WORK(209)
DEFINE_TEST_PROCESS_WORK(210)
DEFINE_TEST_PROCESS_WORK(211)
DEFINE_TEST_PROCESS_WORK(212)
DEFINE_TEST_PROCESS_WORK(213)
DEFINE_TEST_PROCESS_WORK(214)
DEFINE_TEST_PROCESS_WORK(215)
DEFINE_TEST_PROCESS_WORK(216)
DEFINE_TEST_PROCESS_WORK(217)
DEFINE_TEST_PROCESS_WORK(218)
DEFINE_TEST_PROCESS_WORK(219)
DEFINE_TEST_PROCESS_WORK(220)
DEFINE_TEST_PROCESS_WORK(221)
DEFINE_TEST_PROCESS_WORK(222)
DEFINE_TEST_PROCESS_WORK(223)
DEFINE_TEST_PROCESS_WORK(224)
DEFINE_TEST_PROCESS_WORK(225)
DEFINE_TEST_PROCESS_WORK(226)
DEFINE_TEST_PROCESS_WORK(227)
DEFINE_TEST_PROCESS_WORK(228)
DEFINE_TEST_PROCESS_WORK(229)
DEFINE_TEST_PROCESS_WORK(230)
DEFINE_TEST_PROCESS_WORK(231)
DEFINE_TEST_PROCESS_WORK(232)
DEFINE_TEST_PROCESS_WORK(233)
DEFINE_TEST_PROCESS_WORK(234)
DEFINE_TEST_PROCESS_WORK(235)
DEFINE_TEST_PROCESS_WORK(236)
DEFINE_TEST_PROCESS_WORK(237)
DEFINE_TEST_PROCESS_WORK(238)
DEFINE_TEST_PROCESS_WORK(239)
DEFINE_TEST_PROCESS_WORK(240)
DEFINE_TEST_PROCESS_WORK(241)
DEFINE_TEST_PROCESS_WORK(242)
DEFINE_TEST_PROCESS_WORK(243)
DEFINE_TEST_PROCESS_WORK(244)
DEFINE_TEST_PROCESS_WORK(245)
DEFINE_TEST_PROCESS_WORK(246)
DEFINE_TEST_PROCESS_WORK(247)
DEFINE_TEST_PROCESS_WORK(248)
DEFINE_TEST_PROCESS_WORK(249)
DEFINE_TEST_PROCESS_WORK(250)
DEFINE_TEST_PROCESS_WORK(251)
DEFINE_TEST_PROCESS_WORK(252)
DEFINE_TEST_PROCESS_WORK(253)
DEFINE_TEST_PROCESS_WORK(254)
DEFINE_TEST_PROCESS_WORK(255)

DEFINE_TEST_PROCESS_SLEEP(0)
DEFINE_TEST_PROCESS_SLEEP(1)
DEFINE_TEST_PROCESS_SLEEP(2)
DEFINE_TEST_PROCESS_SLEEP(3)
DEFINE_TEST_PROCESS_SLEEP(4)
DEFINE_TEST_PROCESS_SLEEP(5)
DEFINE_TEST_PROCESS_SLEEP(6)
DEFINE_TEST_PROCESS_SLEEP(7)
DEFINE_TEST_PROCESS_SLEEP(8)
DEFINE_TEST_PROCESS_SLEEP(9)
DEFINE_TEST_PROCESS_SLEEP(10)
DEFINE_TEST_PROCESS_SLEEP(11)
DEFINE_TEST_PROCESS_SLEEP(12)
DEFINE_TEST_PROCESS_SLEEP(13)
DEFINE_TEST_PROCESS_SLEEP(14)
DEFINE_TEST_PROCESS_SLEEP(15)
DEFINE_TEST_PROCESS_SLEEP(16)
DEFINE_TEST_PROCESS_SLEEP(17)
DEFINE_TEST_PROCESS_SLEEP(18)
DEFINE_TEST_PROCESS_SLEEP(19)
DEFINE_TEST_PROCESS_SLEEP(20)
DEFINE_TEST_PROCESS_SLEEP(21)
DEFINE_TEST_PROCESS_SLEEP(22)
DEFINE_TEST_PROCESS_SLEEP(23)
DEFINE_TEST_PROCESS_SLEEP(24)
DEFINE_TEST_PROCESS_SLEEP(25)
DEFINE_TEST_PROCESS_SLEEP(26)
DEFINE_TEST_PROCESS_SLEEP(27)
DEFINE_TEST_PROCESS_SLEEP(28)
DEFINE_TEST_PROCESS_SLEEP(29)
DEFINE_TEST_PROCESS_SLEEP(30)
DEFINE_TEST_PROCESS_SLEEP(31)
DEFINE_TEST_PROCESS_SLEEP(32)
DEFINE_TEST_PROCESS_SLEEP(33)
DEFINE_TEST_PROCESS_SLEEP(34)
DEFINE_TEST_PROCESS_SLEEP(35)
DEFINE_TEST_PROCESS_SLEEP(36)
DEFINE_TEST_PROCESS_SLEEP(37)
DEFINE_TEST_PROCESS_SLEEP(38)
DEFINE_TEST_PROCESS_SLEEP(39)
DEFINE_TEST_PROCESS_SLEEP(40)
DEFINE_TEST_PROCESS_SLEEP(41)
DEFINE_TEST_PROCESS_SLEEP(42)
DEFINE_TEST_PROCESS_SLEEP(43)
DEFINE_TEST_PROCESS_SLEEP(44)
DEFINE_TEST_PROCESS_SLEEP(45)
DEFINE_TEST_PROCESS_SLEEP(46)
DEFINE_TEST_PROCESS_SLEEP(47)
DEFINE_TEST_PROCESS_SLEEP(48)
DEFINE_TEST_PROCESS_SLEEP(49)
DEFINE_TEST_PROCESS_SLEEP(50)
DEFINE_TEST_PROCESS_SLEEP(51)
DEFINE_TEST_PROCESS_SLEEP(52)
DEFINE_TEST_PROCESS_SLEEP(53)
DEFINE_TEST_PROCESS_SLEEP(54)
DEFINE_TEST_PROCESS_SLEEP(55)
DEFINE_TEST_PROCESS_SLEEP(56)
DEFINE_TEST_PROCESS_SLEEP(57)
DEFINE_TEST_PROCESS_SLEEP(58)
DEFINE_TEST_PROCESS_SLEEP(59)
DEFINE_TEST_PROCESS_SLEEP(60)
DEFINE_TEST_PROCESS_SLEEP(61)
DEFINE_TEST_PROCESS_SLEEP(62)
DEFINE_TEST_PROCESS_SLEEP(63)
DEFINE_TEST_PROCESS_SLEEP(64)
DEFINE_TEST_PROCESS_SLEEP(65)
DEFINE_TEST_PROCESS_SLEEP(66)
DEFINE_TEST_PROCESS_SLEEP(67)
DEFINE_TEST_PROCESS_SLEEP(68)
DEFINE_TEST_PROCESS_SLEEP(69)
DEFINE_TEST_PROCESS_SLEEP(70)
DEFINE_TEST_PROCESS_SLEEP(71)
DEFINE_TEST_PROCESS_SLEEP(72)
DEFINE_TEST_PROCESS_SLEEP(73)
DEFINE_TEST_PROCESS_SLEEP(74)
DEFINE_TEST_PROCESS_SLEEP(75)
DEFINE_TEST_PROCESS_SLEEP(76)
DEFINE_TEST_PROCESS_SLEEP(77)
DEFINE_TEST_PROCESS_SLEEP(78)
DEFINE_TEST_PROCESS_SLEEP(79)
DEFINE_TEST_PROCESS_SLEEP(80)
DEFINE_TEST_PROCESS_SLEEP(81)
DEFINE_TEST_PROCESS_SLEEP(82)
DEFINE_TEST_PROCESS_SLEEP(83)
DEFINE_TEST_PROCESS_SLEEP(84)
DEFINE_TEST_PROCESS_SLEEP(85)
DEFINE_TEST_PROCESS_SLEEP(86)
DEFINE_TEST_PROCESS_SLEEP(87)
DEFINE_TEST_PROCESS_SLEEP(88)
DEFINE_TEST_PROCESS_SLEEP(89)
DEFINE_TEST_PROCESS_SLEEP(90)
DEFINE_TEST_PROCESS_SLEEP(91)
DEFINE_TEST_PROCESS_SLEEP(92)
DEFINE_TEST_PROCESS_SLEEP(93)
DEFINE_TEST_PROCESS_SLEEP(94)
DEFINE_TEST_PROCESS_SLEEP(95)
DEFINE_TEST_PROCESS_SLEEP(96)
DEFINE_TEST_PROCESS_SLEEP(97)
DEFINE_TEST_PROCESS_SLEEP(98)
DEFINE_TEST_PROCESS_SLEEP(99)
DEFINE_TEST_PROCESS_SLEEP(100)
DEFINE_TEST_PROCESS_SLEEP(101)
DEFINE_TEST_PROCESS_SLEEP(102)
DEFINE_TEST_PROCESS_SLEEP(103)
DEFINE_TEST_PROCESS_SLEEP(104)
DEFINE_TEST_PROCESS_SLEEP(105)
DEFINE_TEST_PROCESS_SLEEP(106)
DEFINE_TEST_PROCESS_SLEEP(107)
DEFINE_TEST_PROCESS_SLEEP(108)
DEFINE_TEST_PROCESS_SLEEP(109)
DEFINE_TEST_PROCESS_SLEEP(110)
DEFINE_TEST_PROCESS_SLEEP(111)
DEFINE_TEST_PROCESS_SLEEP(112)
DEFINE_TEST_PROCESS_SLEEP(113)
DEFINE_TEST_PROCESS_SLEEP(114)
DEFINE_TEST_PROCESS_SLEEP(115)
DEFINE_TEST_PROCESS_SLEEP(116)
DEFINE_TEST_PROCESS_SLEEP(117)
DEFINE_TEST_PROCESS_SLEEP(118)
DEFINE_TEST_PROCESS_SLEEP(119)
DEFINE_TEST_PROCESS_SLEEP(120)
DEFINE_TEST_PROCESS_SLEEP(121)
DEFINE_TEST_PROCESS_SLEEP(122)
DEFINE_TEST_PROCESS_SLEEP(123)
DEFINE_TEST_PROCESS_SLEEP(124)
DEFINE_TEST_PROCESS_SLEEP(125)
DEFINE_TEST_PROCESS_SLEEP(126)
DEFINE_TEST_PROCESS_SLEEP(127)
DEFINE_TEST_PROCESS_SLEEP(128)
DEFINE_TEST_PROCESS_SLEEP(129)
DEFINE_TEST_PROCESS_SLEEP(130)
DEFINE_TEST_PROCESS_SLEEP(131)
DEFINE_TEST_PROCESS_SLEEP(132)
DEFINE_TEST_PROCESS_SLEEP(133)
DEFINE_TEST_PROCESS_SLEEP(134)
DEFINE_TEST_PROCESS_SLEEP(135)
DEFINE_TEST_PROCESS_SLEEP(136)
DEFINE_TEST_PROCESS_SLEEP(137)
DEFINE_TEST_PROCESS_SLEEP(138)
DEFINE_TEST_PROCESS_SLEEP(139)
DEFINE_TEST_PROCESS_SLEEP(140)
DEFINE_TEST_PROCESS_SLEEP(141)
DEFINE_TEST_PROCESS_SLEEP(142)
DEFINE_TEST_PROCESS_SLEEP(143)
DEFINE_TEST_PROCESS_SLEEP(144)
DEFINE_TEST_PROCESS_SLEEP(145)
DEFINE_TEST_PROCESS_SLEEP(146)
DEFINE_TEST_PROCESS_SLEEP(147)
DEFINE_TEST_PROCESS_SLEEP(148)
DEFINE_TEST_PROCESS_SLEEP(149)
DEFINE_TEST_PROCESS_SLEEP(150)
DEFINE_TEST_PROCESS_SLEEP(151)
DEFINE_TEST_PROCESS_SLEEP(152)
DEFINE_TEST_PROCESS_SLEEP(153)
DEFINE_TEST_PROCESS_SLEEP(154)
DEFINE_TEST_PROCESS_SLEEP(155)
DEFINE_TEST_PROCESS_SLEEP(156)
DEFINE_TEST_PROCESS_SLEEP(157)
DEFINE_TEST_PROCESS_SLEEP(158)
DEFINE_TEST_PROCESS_SLEEP(159)
DEFINE_TEST_PROCESS_SLEEP(160)
DEFINE_TEST_PROCESS_SLEEP(161)
DEFINE_TEST_PROCESS_SLEEP(162)
DEFINE_TEST_PROCESS_SLEEP(163)
DEFINE_TEST_PROCESS_SLEEP(164)
DEFINE_TEST_PROCESS_SLEEP(165)
DEFINE_TEST_PROCESS_SLEEP(166)
DEFINE_TEST_PROCESS_SLEEP(167)
DEFINE_TEST_PROCESS_SLEEP(168)
DEFINE_TEST_PROCESS_SLEEP(169)
DEFINE_TEST_PROCESS_SLEEP(170)
DEFINE_TEST_PROCESS_SLEEP(171)
DEFINE_TEST_PROCESS_SLEEP(172)
DEFINE_TEST_PROCESS_SLEEP(173)
DEFINE_TEST_PROCESS_SLEEP(174)
DEFINE_TEST_PROCESS_SLEEP(175)
DEFINE_TEST_PROCESS_SLEEP(176)
DEFINE_TEST_PROCESS_SLEEP(177)
DEFINE_TEST_PROCESS_SLEEP(178)
DEFINE_TEST_PROCESS_SLEEP(179)
DEFINE_TEST_PROCESS_SLEEP(180)
DEFINE_TEST_PROCESS_SLEEP(181)
DEFINE_TEST_PROCESS_SLEEP(182)
DEFINE_TEST_PROCESS_SLEEP(183)
DEFINE_TEST_PROCESS_SLEEP(184)
DEFINE_TEST_PROCESS_SLEEP(185)
DEFINE_TEST_PROCESS_SLEEP(186)
DEFINE_TEST_PROCESS_SLEEP(187)
DEFINE_TEST_PROCESS_SLEEP(188)
DEFINE_TEST_PROCESS_SLEEP(189)
DEFINE_TEST_PROCESS_SLEEP(190)
DEFINE_TEST_PROCESS_SLEEP(191)
DEFINE_TEST_PROCESS_SLEEP(192)
DEFINE_TEST_PROCESS_SLEEP(193)
DEFINE_TEST_PROCESS_SLEEP(194)
DEFINE_TEST_PROCESS_SLEEP(195)
DEFINE_TEST_PROCESS_SLEEP(196)
DEFINE_TEST_PROCESS_SLEEP(197)
DEFINE_TEST_PROCESS_SLEEP(198)
DEFINE_TEST_PROCESS_SLEEP(199)
DEFINE_TEST_PROCESS_SLEEP(200)
DEFINE_TEST_PROCESS_SLEEP(201)
DEFINE_TEST_PROCESS_SLEEP(202)
DEFINE_TEST_PROCESS_SLEEP(203)
DEFINE_TEST_PROCESS_SLEEP(204)
DEFINE_TEST_PROCESS_SLEEP(205)
DEFINE_TEST_PROCESS_SLEEP(206)
DEFINE_TEST_PROCESS_SLEEP(207)
DEFINE_TEST_PROCESS_SLEEP(208)
DEFINE_TEST_PROCESS_SLEEP(209)
DEFINE_TEST_PROCESS_SLEEP(210)
DEFINE_TEST_PROCESS_SLEEP(211)
DEFINE_TEST_PROCESS_SLEEP(212)
DEFINE_TEST_PROCESS_SLEEP(213)
DEFINE_TEST_PROCESS_SLEEP(214)
DEFINE_TEST_PROCESS_SLEEP(215)
DEFINE_TEST_PROCESS_SLEEP(216)
DEFINE_TEST_PROCESS_SLEEP(217)
DEFINE_TEST_PROCESS_SLEEP(218)
DEFINE_TEST_PROCESS_SLEEP(219)
DEFINE_TEST_PROCESS_SLEEP(220)
DEFINE_TEST_PROCESS_SLEEP(221)
DEFINE_TEST_PROCESS_SLEEP(222)
DEFINE_TEST_PROCESS_SLEEP(223)
DEFINE_TEST_PROCESS_SLEEP(224)
DEFINE_TEST_PROCESS_SLEEP(225)
DEFINE_TEST_PROCESS_SLEEP(226)
DEFINE_TEST_PROCESS_SLEEP(227)
DEFINE_TEST_PROCESS_SLEEP(228)
DEFINE_TEST_PROCESS_SLEEP(229)
DEFINE_TEST_PROCESS_SLEEP(230)
DEFINE_TEST_PROCESS_SLEEP(231)
DEFINE_TEST_PROCESS_SLEEP(232)
DEFINE_TEST_PROCESS_SLEEP(233)
DEFINE_TEST_PROCESS_SLEEP(234)
DEFINE_TEST_PROCESS_SLEEP(235)
DEFINE_TEST_PROCESS_SLEEP(236)
DEFINE_TEST_PROCESS_SLEEP(237)
DEFINE_TEST_PROCESS_SLEEP(238)
DEFINE_TEST_PROCESS_SLEEP(239)
DEFINE_TEST_PROCESS_SLEEP(240)
DEFINE_TEST_PROCESS_SLEEP(241)
DEFINE_TEST_PROCESS_SLEEP(242)
DEFINE_TEST_PROCESS_SLEEP(243)
DEFINE_TEST_PROCESS_SLEEP(244)
DEFINE_TEST_PROCESS_SLEEP(245)
DEFINE_TEST_PROCESS_SLEEP(246)
DEFINE_TEST_PROCESS_SLEEP(247)
DEFINE_TEST_PROCESS_SLEEP(248)
DEFINE_TEST_PROCESS_SLEEP(249)
DEFINE_TEST_PROCESS_SLEEP(250)
DEFINE_TEST_PROCESS_SLEEP(251)
DEFINE_TEST_PROCESS_SLEEP(252)
DEFINE_TEST_PROCESS_SLEEP(253)
DEFINE_TEST_PROCESS_SLEEP(254)
DEFINE_TEST_PROCESS_SLEEP(255)
